source 'https://cdn.cocoapods.org'

target_version = '13.2'
platform :ios, target_version
use_frameworks!

def shared_pods
  
end

target 'TWHub' do
  shared_pods
end

target 'Template' do
  shared_pods
end

target 'CohesionIB' do
  shared_pods
  
  target 'CohesionIBTests' do
    inherit! :search_paths
  end

  target 'CohesionIBUITests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # force minimum target to mute xcode warnings
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = target_version
    end
  end
end
